name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test (${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        include:
          - ruby: "3.2"
            coverage: "true"
    env:
      COVERAGE: ${{matrix.coverage}}
      COVERAGE_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run all tests
      run: bundle exec rake
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      if: env.COVERAGE == 'true' && env.COVERAGE_TOKEN != ''
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: coverage/coverage.xml

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: test
    if: contains(github.ref, 'tags')
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Publish gems to Rubygems
      run: |
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
